// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsqVbzYcksbTxan5v66KagIYfXq2-M3e4',
    appId: '1:147960043695:web:a2326a9e041d1d807d1c5a',
    messagingSenderId: '147960043695',
    projectId: 'insta-788a0',
    authDomain: 'insta-788a0.firebaseapp.com',
    storageBucket: 'insta-788a0.firebasestorage.app',
    measurementId: 'G-Q3B7JTT72B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAroz_mX0u1eHxvcUNvumys3gbm1Yv2t0o',
    appId: '1:147960043695:android:c9ed84c3ff3619157d1c5a',
    messagingSenderId: '147960043695',
    projectId: 'insta-788a0',
    storageBucket: 'insta-788a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtsoLx67-aKMQaWZn9lhasEcxjljCjPfs',
    appId: '1:147960043695:ios:9cd02d53005cf7957d1c5a',
    messagingSenderId: '147960043695',
    projectId: 'insta-788a0',
    storageBucket: 'insta-788a0.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtsoLx67-aKMQaWZn9lhasEcxjljCjPfs',
    appId: '1:147960043695:ios:9cd02d53005cf7957d1c5a',
    messagingSenderId: '147960043695',
    projectId: 'insta-788a0',
    storageBucket: 'insta-788a0.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsqVbzYcksbTxan5v66KagIYfXq2-M3e4',
    appId: '1:147960043695:web:a46e5cd189333d817d1c5a',
    messagingSenderId: '147960043695',
    projectId: 'insta-788a0',
    authDomain: 'insta-788a0.firebaseapp.com',
    storageBucket: 'insta-788a0.firebasestorage.app',
    measurementId: 'G-5E57GJGXR2',
  );
}
